version: '2'

services:
  web-vote-app:
    image: web-vote-app:latest
    environment:
      WEB_VOTE_NUMBER: "01"
      constraint:node: "=frontend01"

  vote-worker:
    image: vote-worker:latest
    environment:
      FROM_REDIS_HOST: 1
      TO_REDIS_HOST: 1

  results-app:
    image: results-app:latest

  redis01:
    image: redis:3

  store:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg8675309
